### ISSUE TITLE
PIT Interface

### ISSUE THREAD

**Issue by Sploder12** [makeopensource/mOS#10]
The PIT (Programable Interval Timer) is a useful piece of hardware used for many timing related tasks.

The functions we're interested in are those associated with IRQ0 (the 0th hardware interrupt vector).
The must-haves are:
- a way to modify the frequency of IRQ0
- a basic implementation of `sleep`
- a way to keep track of time 

the osdev wiki has a detailed article [here](https://wiki.osdev.org/Programmable_Interval_Timer)

**Comment by shawnz99** [comment]
I'll give this a go
