### ISSUE TITLE
Create Style Guide

### ISSUE THREAD

**Issue by Sploder12** [makeopensource/mOS#21]
@bicknrown mentioned this during the 3/14/2023 weekly meeting.

Different programmers have different styles, which if not made consistent, will make a project at minimum look strange, and at worse unreadable. To combat this issue a style guide should be created. (Ask @bicknrown for more details on this)

**Comment by Sploder12** [comment]
clang-format may be worth looking into.

**Comment by emilkovacev** [comment]
I have a PR ready for this, it includes a clang format file and makefile command for formatting all code at once! I'd like to wait to clean the `main` branch before making the PR though

**Comment by emilkovacev** [comment]
Some resources I used:
- [RedHat clang-format guide](https://developers.redhat.com/articles/2022/02/25/enforce-code-consistency-clang-format#explore_your_code_styling_options)
- [clang-format-configurator](https://zed0.co.uk/clang-format-configurator/) -> recommended by RedHat! It's great for generating config files

**Comment by emilkovacev** [comment]
Can we close this issue?
